# Generated by Django 5.0.6 on 2024-06-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_answer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_anon',
        ),
    ]
