# Generated by Django 5.0.6 on 2024-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post_shared_alter_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anon',
            field=models.BooleanField(default=True),
        ),
    ]
