# Generated by Django 5.0.6 on 2024-07-04 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_question_is_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(max_length=3072),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(help_text='Ask me anything', max_length=1024, validators=[django.core.validators.MinLengthValidator(4, 'Question must contain at least 4 characters!')]),
        ),
    ]
