# Generated by Django 5.0.6 on 2024-07-11 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_post_liked_alter_post_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
