# Generated by Django 5.0.6 on 2024-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_post_liked_alter_post_shared'),
        ('user', '0003_profile_question_helper_profile_silenced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_likes', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_shares', to='user.profile'),
        ),
    ]
