# Generated by Django 5.0.6 on 2024-07-09 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_blocked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='question_helper',
            field=models.TextField(blank=True, default='Ask me anything !', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='silenced',
            field=models.ManyToManyField(blank=True, related_name='silenced_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
